/**
 * Lunar Frontier — Terrestrial Proving Grounds racetrack (Spec 17 §3,
 * TASK-PLAY-064d).
 *
 * A self-contained, procedurally generated ~1,200 m closed asphalt circuit
 * built entirely from hand-rolled vertex data, so it runs identically on a
 * `NullEngine` (headless CI) and a real WebGL2/WebGPU context. The circuit
 * is generated by *curvature integration*: a piecewise κ(s) profile
 * (straight segments + constant-curvature arcs) is integrated at uniform
 * arc-length steps, so every section lands on an exact heading and the loop
 * closes back on the start/finish line with a matching tangent (verified
 * numerically to well under a millimetre).
 *
 * Circuit sections (Spec 17 §3.1):
 *   1. Straightaway Speed Trap   — 250 m flat straight; the trap zone
 *      (s = 60…210 m) records peak speed through the flying gantry.
 *   2. Banked High-Speed Sweeper — 180° arc, radius 75 m, banked inwards at
 *      10° (0.174533 rad) with 20 m ease-in/ease-out ramps.
 *   3. Slalom S-Curves           — three alternating ±90° transitions,
 *      radius 30 m.
 *   4. Hairpin & Agility Zone    — tight 180° arc, radius 15 m, with a
 *      run-off tarmac disc filling the inside of the turn.
 *   5. Camber & Elevation Crest  — climb straight (0 → 5 m), a compression
 *      dip just before the brow, a 180° arc on the 5 m plateau, then a
 *      descent straight back to datum closing the loop.
 *
 * Track surface: 12 m asphalt ribbon, 1.5 m red/white rumble-strip curbs on
 * both sides, painted edge lines and a dashed centreline. Bank crossfall is
 * applied to every emitted surface point (`z += lRight · tan(bank)`), so
 * curbs, markings and checkpoint gantries all ride the banking.
 *
 * Timing: a Babylon-free {@link LapTimingSystem} state machine (sectors as
 * sequential checkpoint gates, start/finish detection with wrap handling,
 * speed-trap capture) driven through {@link ProvingGroundsScene.stepLapTiming}.
 *
 * Frame convention matches the rest of the codebase: physics world metres
 * `(x, y, z↑)`; meshes are emitted into Babylon's y-up frame via
 * {@link worldToBabylon}.
 */

import '@babylonjs/core/Shaders/default.vertex.js';
import '@babylonjs/core/Shaders/default.fragment.js';
import '@babylonjs/core/Shaders/pbr.vertex.js';
import '@babylonjs/core/Shaders/pbr.fragment.js';

import { NullEngine } from '@babylonjs/core/Engines/nullEngine.js';
import type { AbstractEngine } from '@babylonjs/core/Engines/abstractEngine.js';
import { Color3, Color4 } from '@babylonjs/core/Maths/math.color.js';
import { Vector3 } from '@babylonjs/core/Maths/math.vector.js';
import { Scene } from '@babylonjs/core/scene.js';
import { DirectionalLight } from '@babylonjs/core/Lights/directionalLight.js';
import { HemisphericLight } from '@babylonjs/core/Lights/hemisphericLight.js';
import { PBRMaterial } from '@babylonjs/core/Materials/PBR/pbrMaterial.js';
import { Mesh } from '@babylonjs/core/Meshes/mesh.js';
import { VertexData } from '@babylonjs/core/Meshes/mesh.vertexData.js';
import { MeshBuilder } from '@babylonjs/core/Meshes/meshBuilder.js';

import { worldToBabylon } from './CameraRig.ts';

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/**
 * One arc-length sample of the track centreline spline (Spec 17 §3.3).
 * Positions are physics-frame metres (x east, y north, z up).
 */
export interface TrackWaypoint {
  x: number;
  y: number;
  z: number;
  /** Continuous tangent heading at this sample, radians (0 = +x). */
  headingRad: number;
  /**
   * Crossfall bank angle, radians. Positive raises the *right* edge (i.e.
   * banks inwards through a left-hand turn): the surface follows
   * `z(lRight) = zCentre + lRight · tan(bankAngleRad)`.
   */
  bankAngleRad: number;
  /** Asphalt width at this sample, metres (12 m circuit-wide). */
  trackWidthM: number;
  /** True at the start/finish line and each sector-split gate. */
  isCheckpoint: boolean;
  /** Timing sector this sample belongs to: 1, 2 or 3 (Spec 17 §3.3). */
  sectorIndex: 1 | 2 | 3;
  /** Circuit section index: 1..5 (Spec 17 §3.1). */
  sectionIndex: 1 | 2 | 3 | 4 | 5;
  /** Arc length from the start/finish line, metres, 0 ≤ s < lengthM. */
  arcLengthM: number;
}

/** Descriptive metadata for one of the five circuit sections. */
export interface CircuitSectionInfo {
  index: 1 | 2 | 3 | 4 | 5;
  name: string;
  kind: 'straightaway' | 'banked-sweeper' | 'slalom' | 'hairpin' | 'crest';
  /** Inclusive arc-length span, metres. */
  startS: number;
  endS: number;
  lengthM: number;
  /** Peak bank angle inside the section, radians (absolute). */
  peakBankRad: number;
  /** Peak elevation inside the section, metres. */
  peakElevationM: number;
}

/**
 * Lap / sector / speed-trap state snapshot (Spec 17 §3.3), consumed by
 * `LunarHUD.updateLapTelemetry()` and the client frame loop.
 */
export interface LapTelemetry {
  /** Lap in progress: starts at 1, increments on each valid crossing. */
  currentLap: number;
  /** Elapsed time on the current lap, seconds. */
  currentLapTimeS: number;
  /** Best completed lap, seconds; null until the first valid lap. */
  bestLapTimeS: number | null;
  /** Most recent completed lap, seconds; null before the first. */
  lastLapTimeS: number | null;
  /** Completed sector splits of the *current* lap, seconds (in order). */
  sectorTimesS: number[];
  /** Instantaneous road speed, km/h. */
  currentSpeedKmh: number;
  /** Top speed achieved since the timer was created/reset, km/h. */
  topSpeedKmh: number;
  /** Best speed-trap capture, km/h; null until captured. */
  speedTrapKmh: number | null;
  /** Last sector split minus the same sector of the previous lap, seconds
   *  (negative = faster). Null until comparable. */
  sectorDeltaS: number | null;
}

/** Locator handed to {@link LapTimingSystem}: where is (x, y) on the track? */
export type TrackLocator = (
  x: number,
  y: number,
) => { s: number; lateralM: number };

export interface LapTimingOptions {
  /** Total closed-loop length, metres. */
  trackLengthM: number;
  /** Gate positions by arc length; index 0 MUST be the start/finish line. */
  gateS: readonly number[];
  /** Speed-trap zone `[startS, endS]` on the straight (no wrap). */
  trapZone: readonly [number, number];
  /**
   * True (default) when the driver starts armed on the finish line, i.e.
   * the first sector gate is live immediately. Set false when the timer
   * starts mid-circuit: gates then arm only after the first crossing.
   */
  armAtStart?: boolean;
  /** Gate/trap detection is suppressed beyond this |lateral| offset, metres. */
  offTrackM?: number;
}

export interface ProvingGroundsSceneOptions {
  /** Set false inside an already-lit world (ClientApp) — skips atmosphere. */
  standaloneAtmosphere?: boolean;
  /** Skip console chatter in CI. */
  silent?: boolean;
}

// ---------------------------------------------------------------------------
// Circuit constants (Spec 17 §3.1)
// ---------------------------------------------------------------------------

/** Nominal loop length, metres. The generated loop closes on it to <1 mm. */
export const TRACK_TOTAL_LENGTH_M = 1200;

/** Asphalt width, metres. */
export const TRACK_WIDTH_M = 12;

/** Rumble-strip curb width, metres (outside the asphalt edge). */
export const CURB_WIDTH_M = 1.5;

/** Section 2 — banked sweeper: 180° arc, radius 75 m, banked in at 10°. */
export const SWEEPER_RADIUS_M = 75;
export const SWEEPER_BANK_RAD = 0.17453292519943295; // 10° = π/18
/** Ease-in / ease-out length of the banking ramp, metres. */
export const BANK_EASE_M = 20;

/** Section 3 — slalom: three alternating ±90° transitions, radius 30 m. */
export const SLALOM_RADIUS_M = 30;

/** Section 4 — hairpin: 180° arc, radius 15 m, run-off tarmac inside. */
export const HAIRPIN_RADIUS_M = 15;

/** Section 5 — crest: elevation rise, metres. */
export const CREST_ELEVATION_M = 5;
/** Crest compression dip depth just before the brow, metres. */
export const CREST_DIP_M = 0.35;

/** Closing-loop arc radii solved so the circuit rejoins the finish line. */
export const CLOSING_ARC_R1 = 80; // 180° arc across the crest plateau
export const CLOSING_ARC_R2 = 30; // 90° final return arc

/** Speed-trap zone on the main straight, arc-length metres. */
export const SPEED_TRAP_ZONE: readonly [number, number] = [60, 210];

// Arc-length section boundaries (start of each section), derived from the
// mandated geometry so they can never drift out of sync with the profile.
const S1_LEN = 250;
const S2_LEN = Math.PI * SWEEPER_RADIUS_M;
const S3_LEN = (3 * Math.PI * SLALOM_RADIUS_M) / 2;
const S4_LEN = Math.PI * HAIRPIN_RADIUS_M;
const S_S2 = S1_LEN;
const S_S3 = S_S2 + S2_LEN;
const S_S4 = S_S3 + S3_LEN;
const S_S5 = S_S4 + S4_LEN;

/**
 * Crest climb straight (inside Section 5). The Section 5 remainder is
 * `climb + π·R1 + (climb + 30) + π·R2/2` metres; solving against the
 * mandated 1,200 m total gives an exactly closing loop:
 *   climb = (1200 − s(S5) − π(R1 + R2/2) − 30) / 2
 */
const S5_CLIMB_M =
  (TRACK_TOTAL_LENGTH_M - S_S5 - Math.PI * (CLOSING_ARC_R1 + CLOSING_ARC_R2 / 2) - 30) / 2;
/** Arc length where the descent begins — the crest brow (gate 2 sits here). */
const S_CREST = S_S5 + S5_CLIMB_M + Math.PI * CLOSING_ARC_R1;

/** Start/finish line + sector-split gates by arc length (index 0 = finish). */
export const GATE_S: readonly number[] = [0, S_S3, S_CREST];

/** Timing sector for an arc length: [0,g1) → 1, [g1,g2) → 2, [g2,L) → 3. */
export function sectorAtS(s: number): 1 | 2 | 3 {
  const L = TRACK_TOTAL_LENGTH_M;
  const w = ((s % L) + L) % L;
  if (w < GATE_S[1]) return 1;
  if (w < GATE_S[2]) return 2;
  return 3;
}

/** Circuit section (Spec 17 §3.1) for an arc length. */
export function sectionAtS(s: number): 1 | 2 | 3 | 4 | 5 {
  const L = TRACK_TOTAL_LENGTH_M;
  const w = ((s % L) + L) % L;
  if (w < S_S2) return 1;
  if (w < S_S3) return 2;
  if (w < S_S4) return 3;
  if (w < S_S5) return 4;
  return 5;
}

// ---------------------------------------------------------------------------
// Track profile functions (Babylon-free)
// ---------------------------------------------------------------------------

function clamp(v: number, lo: number, hi: number): number {
  return v < lo ? lo : v > hi ? hi : v;
}

/** Hermite smoothstep on [0, 1]. */
function smoothstep(t: number): number {
  const u = clamp(t, 0, 1);
  return u * u * (3 - 2 * u);
}

/** Wrap any arc length into [0, L). */
export function wrapTrackS(s: number): number {
  const L = TRACK_TOTAL_LENGTH_M;
  return ((s % L) + L) % L;
}

/**
 * Centreline elevation profile, z-up metres. Flat datum everywhere except
 * Section 5: a smooth 0 → 5 m climb, a plateau (with a compression dip just
 * before the brow), and a smooth descent back to datum.
 */
export function elevationAtS(s: number): number {
  const w = wrapTrackS(s);
  if (w < S_S5) return 0;
  const s5 = w - S_S5;
  const arcEnd = S5_CLIMB_M + Math.PI * CLOSING_ARC_R1;
  const descendEnd = arcEnd + S5_CLIMB_M + 30;
  if (s5 < S5_CLIMB_M) {
    return CREST_ELEVATION_M * smoothstep(s5 / S5_CLIMB_M);
  }
  if (s5 < arcEnd) {
    const toBrow = arcEnd - s5;
    if (toBrow < 15) {
      const u = 1 - toBrow / 15;
      const s2 = Math.sin(Math.PI * u);
      return CREST_ELEVATION_M - CREST_DIP_M * s2 * s2;
    }
    return CREST_ELEVATION_M;
  }
  if (s5 < descendEnd) {
    return CREST_ELEVATION_M * (1 - smoothstep((s5 - arcEnd) / (S5_CLIMB_M + 30)));
  }
  return 0;
}

/**
 * Bank-angle profile, radians (positive = right edge raised = banked inwards
 * through the left-hand sweeper). Zero everywhere but Section 2, easing in
 * and out over {@link BANK_EASE_M}.
 */
export function bankAtS(s: number): number {
  const w = wrapTrackS(s);
  if (w < S_S2 || w >= S_S3) return 0;
  const into = w - S_S2;
  const out = S_S3 - w;
  return SWEEPER_BANK_RAD * Math.min(1, Math.min(into, out) / BANK_EASE_M);
}

// ---------------------------------------------------------------------------
// Curvature-integration generator
// ---------------------------------------------------------------------------

interface KappaSegment {
  /** Segment length, metres. */
  length: number;
  /** Total heading change across the segment, radians (signed). */
  dTheta: number;
}

/**
 * The κ(s) profile of the whole circuit: straight segments (dTheta 0) and
 * constant-curvature arcs. The dTheta budget sums to exactly 360°, and the
 * segment lengths were solved (see {@link S5_CLIMB_M}) so the integrated
 * endpoint lands back on the start/finish line position AND heading.
 */
export function buildKappaProfile(): KappaSegment[] {
  return [
    // Section 1 — 250 m flat straight (the speed trap lives inside it).
    { length: S1_LEN, dTheta: 0 },
    // Section 2 — 180° banked sweeper, R 75 (left).
    { length: S2_LEN, dTheta: Math.PI },
    // Section 3 — slalom: +90 / −90 / +90, R 30.
    { length: (Math.PI * SLALOM_RADIUS_M) / 2, dTheta: Math.PI / 2 },
    { length: (Math.PI * SLALOM_RADIUS_M) / 2, dTheta: -Math.PI / 2 },
    { length: (Math.PI * SLALOM_RADIUS_M) / 2, dTheta: Math.PI / 2 },
    // Section 4 — hairpin: 180° right, R 15.
    { length: S4_LEN, dTheta: -Math.PI },
    // Section 5 — crest climb, 180° plateau arc R 80 (left), descent, then a
    // 90° return arc R 30 that closes the loop heading-first.
    { length: S5_CLIMB_M, dTheta: 0 },
    { length: Math.PI * CLOSING_ARC_R1, dTheta: Math.PI },
    { length: S5_CLIMB_M + 30, dTheta: 0 },
    { length: (Math.PI * CLOSING_ARC_R2) / 2, dTheta: Math.PI / 2 },
  ];
}

interface CentrelineSample {
  s: number;
  x: number;
  y: number;
  heading: number;
}

/**
 * Midpoint integration of the κ profile at uniform arc-length steps of
 * about `ds` metres. Returns samples covering [0, L] — the final sample
 * equals the first within integration tolerance.
 */
export function integrateCentreline(ds = 0.5): CentrelineSample[] {
  const segs = buildKappaProfile();
  const out: CentrelineSample[] = [{ s: 0, x: 0, y: 0, heading: 0 }];
  let s = 0;
  let theta = 0;
  let x = 0;
  let y = 0;
  for (const seg of segs) {
    const n = Math.max(1, Math.round(seg.length / ds));
    const d = seg.length / n;
    const k = seg.dTheta / seg.length;
    for (let i = 0; i < n; i++) {
      // `theta` already accumulates, so the midpoint only leads by half a step.
      const mid = theta + k * d * 0.5;
      x += Math.cos(mid) * d;
      y += Math.sin(mid) * d;
      s += d;
      theta += k * d;
      out.push({ s, x, y, heading: theta });
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// LapTimingSystem — Babylon-free lap/sector state machine
// ---------------------------------------------------------------------------

/**
 * Sequential-gate lap timer (Spec 17 §3.3).
 *
 * Detection model: every {@link step} locates the driver on the centreline
 * (arc length s, signed lateral offset) and tests the s-interval swept since
 * the previous step against the gates. Motion must be forward — reversing
 * back across the line never completes a lap. Gates must be taken in order
 * (finish → gate 1 → gate 2 → finish); a lap that skips a gate is not
 * completed — the next crossing re-arms the sequence and discards its
 * partial splits. The speed trap captures peak speed inside its zone.
 */
export class LapTimingSystem {
  private readonly opts: Required<LapTimingOptions>;
  /** Wired by `ProvingGroundsScene.createLapTimer()` (or by tests). */
  public locate: TrackLocator | undefined;
  private disposed = false;

  private t = 0;
  private lapStartT = 0;
  private lap = 1;
  /** Index into gateS of the next gate that registers (0 = finish line). */
  private nextGate: number;
  private splits: number[] = [];
  private prevLapSplits: number[] | null = null;
  private lastLap: number | null = null;
  private bestLap: number | null = null;
  private speedKmh = 0;
  private topKmh = 0;
  private trapKmh: number | null = null;
  private delta: number | null = null;
  private prevS: number | null = null;
  private snapshot: LapTelemetry;

  constructor(options: LapTimingOptions) {
    this.opts = { armAtStart: true, offTrackM: 45, ...options };
    this.nextGate = this.opts.armAtStart ? 1 % options.gateS.length : 0;
    this.snapshot = this.compose();
  }

  /**
   * Advance the timer one frame from a position sample.
   * @param dt       frame delta, seconds (clamped to 0…0.25)
   * @param x, y     driver position, physics-frame metres
   * @param speedMps instantaneous road speed, m/s
   */
  step(dt: number, x: number, y: number, speedMps: number): LapTelemetry {
    if (this.disposed) return { ...this.snapshot };
    const d = clamp(Number.isFinite(dt) ? dt : 0, 0, 0.25);
    this.t += d;

    const kmh = Number.isFinite(speedMps) ? Math.abs(speedMps) * 3.6 : 0;
    this.speedKmh = kmh;
    if (kmh > this.topKmh) this.topKmh = kmh;

    if (this.locate === undefined) {
      // No track wired: keep timers running, nothing to detect.
      this.snapshot = this.compose();
      return { ...this.snapshot };
    }

    const { s, lateralM } = this.locate(x, y);
    const onTrack = Math.abs(lateralM) <= this.opts.offTrackM;
    const prev = this.prevS;
    this.prevS = s;

    if (prev !== null && onTrack && Number.isFinite(s)) {
      const L = this.opts.trackLengthM;
      const gates = this.opts.gateS;

      // Speed trap: capture the peak while inside the zone.
      const [t0, t1] = this.opts.trapZone;
      if (s >= t0 && s <= t1) {
        this.trapKmh = this.trapKmh === null ? kmh : Math.max(this.trapKmh, kmh);
      }

      // Start/finish: high→low arc-length wrap == forward crossing of s = 0.
      const crossedFinish = prev > L * 0.85 && s < L * 0.15;
      if (crossedFinish) this.handleFinishCrossing();

      // Sector gates: forward sweep across the gate's s, in sequence. A
      // sweep may not span more than half the lap — a giant jump (teleport,
      // or a backwards hop near the line masquerading as a wrap) is not a
      // legitimate gate crossing and never registers.
      const swept = s - prev;
      if (swept >= 0 && swept < L / 2) {
        if (!crossedFinish || this.nextGate !== 0) {
          for (let g = 1; g < gates.length; g++) {
            if (g !== this.nextGate) continue;
            if (prev < gates[g] && s >= gates[g]) {
              this.registerSector(g);
              break;
            }
          }
        }
      }
    }

    this.snapshot = this.compose();
    return { ...this.snapshot };
  }

  /** Current telemetry without stepping. */
  getTelemetry(): LapTelemetry {
    return { ...this.snapshot };
  }

  /** Full reset: lap counters, best/last, splits, trap and top speed. */
  reset(): void {
    this.t = 0;
    this.lapStartT = 0;
    this.lap = 1;
    this.nextGate = this.opts.armAtStart ? 1 % this.opts.gateS.length : 0;
    this.splits = [];
    this.prevLapSplits = null;
    this.lastLap = null;
    this.bestLap = null;
    this.speedKmh = 0;
    this.topKmh = 0;
    this.trapKmh = null;
    this.delta = null;
    this.prevS = null;
    this.snapshot = this.compose();
  }

  /** The gate index that must be crossed next (0 = finish line). */
  get pendingGateIndex(): number {
    return this.nextGate;
  }

  /** Idempotent teardown; further steps are no-ops returning the snapshot. */
  dispose(): void {
    this.disposed = true;
    this.locate = undefined;
  }

  // -- internals ---------------------------------------------------------------

  private handleFinishCrossing(): void {
    if (this.nextGate !== 0) {
      // Crossed the line without completing the gate sequence (a mid-lap
      // teleport, or the very first crossing of a cold start placed off the
      // line): treat as the *start* of a fresh lap, not a completion.
      this.splits = [];
      this.lapStartT = this.t;
      this.nextGate = 1 % this.opts.gateS.length;
      return;
    }
    const lapTime = this.t - this.lapStartT;
    this.lastLap = lapTime;
    this.bestLap = this.bestLap === null ? lapTime : Math.min(this.bestLap, lapTime);
    this.prevLapSplits = [...this.splits];
    this.splits = [];
    this.lap += 1;
    this.lapStartT = this.t;
    this.nextGate = 1 % this.opts.gateS.length;
  }

  private registerSector(gateIndex: number): void {
    let prior = 0;
    for (const v of this.splits) prior += v;
    this.splits.push(this.t - this.lapStartT - prior);
    const prevSame = this.prevLapSplits !== null ? this.prevLapSplits[gateIndex - 1] : undefined;
    this.delta =
      prevSame !== undefined && Number.isFinite(prevSame)
        ? this.splits[this.splits.length - 1] - prevSame
        : null;
    this.nextGate = (gateIndex + 1) % this.opts.gateS.length;
  }

  private compose(): LapTelemetry {
    return {
      currentLap: this.lap,
      currentLapTimeS: Math.max(0, this.t - this.lapStartT),
      bestLapTimeS: this.bestLap,
      lastLapTimeS: this.lastLap,
      sectorTimesS: [...this.splits],
      currentSpeedKmh: this.speedKmh,
      topSpeedKmh: this.topKmh,
      speedTrapKmh: this.trapKmh,
      sectorDeltaS: this.delta,
    };
  }
}

// ---------------------------------------------------------------------------
// Mesh accumulation helper (one merged mesh per material)
// ---------------------------------------------------------------------------

interface QuadAccumulator {
  positions: number[];
  normals: number[];
  uvs: number[];
  indices: number[];
}

function newAccumulator(): QuadAccumulator {
  return { positions: [], normals: [], uvs: [], indices: [] };
}

// ---------------------------------------------------------------------------
// ProvingGroundsScene
// ---------------------------------------------------------------------------

/**
 * The proving-grounds environment: circuit geometry + PBR materials +
 * checkpoint marker volumes in one Babylon `Scene`, plus the centreline
 * spline query surface and the lap-timing state machine. Headless-safe:
 * {@link init} accepts a Scene, a raw engine (e.g. `NullEngine`), or nothing
 * at all (self-owned `NullEngine` fallback).
 */
export class ProvingGroundsScene {
  /** Centreline arc spacing used by the integrator, metres. */
  readonly sampleDs: number;

  private readonly samples: CentrelineSample[];
  private readonly totalLengthM: number;
  private readonly sections: CircuitSectionInfo[];
  private readonly waypoints: TrackWaypoint[];
  /** Coarse spatial hash (cell → sample indices) for nearest lookups. */
  private readonly grid = new Map<string, number[]>();
  private readonly gridCell = 40;

  // Babylon surface (built in init()).
  private scene: Scene | null = null;
  private ownedEngine: AbstractEngine | null = null;
  private ownsScene = false;
  private built = false;
  private disposed = false;
  private meshes: Mesh[] = [];
  private materials: PBRMaterial[] = [];
  private lights: Array<DirectionalLight | HemisphericLight> = [];

  private asphaltMaterial: PBRMaterial | null = null;
  private paintWhiteMaterial: PBRMaterial | null = null;
  private paintRedMaterial: PBRMaterial | null = null;
  private paintYellowMaterial: PBRMaterial | null = null;
  private gravelMaterial: PBRMaterial | null = null;
  private gateMaterial: PBRMaterial | null = null;
  private gateFinishMaterial: PBRMaterial | null = null;

  private timer: LapTimingSystem | null = null;
  private readonly silent: boolean;
  private readonly standaloneAtmosphere: boolean;

  constructor(options: ProvingGroundsSceneOptions = {}) {
    this.silent = options.silent ?? false;
    this.standaloneAtmosphere = options.standaloneAtmosphere ?? true;
    this.sampleDs = 0.5;
    this.samples = integrateCentreline(this.sampleDs);
    // Integration lands within millimetres of the nominal 1,200 m; keep the
    // measured value as the authoritative loop length for s bookkeeping.
    this.totalLengthM = this.samples[this.samples.length - 1].s;
    this.waypoints = this.buildWaypoints();
    this.sections = this.buildSections();
    this.buildGrid();
  }

  // -- lifecycle ---------------------------------------------------------------

  /** Build all meshes/materials/lights into a scene. Idempotent. */
  init(sceneOrEngine?: Scene | AbstractEngine | null): this {
    if (this.disposed) throw new Error('ProvingGroundsScene: init() after dispose()');
    if (this.built) return this;

    if (sceneOrEngine instanceof Scene) {
      this.scene = sceneOrEngine;
    } else if (sceneOrEngine !== null && sceneOrEngine !== undefined) {
      this.scene = new Scene(sceneOrEngine);
      this.ownsScene = true;
    } else if (typeof window === 'undefined') {
      const engine = new NullEngine();
      this.ownedEngine = engine;
      this.scene = new Scene(engine);
      this.ownsScene = true;
    } else {
      throw new Error('ProvingGroundsScene.init: browser needs a Scene or Engine');
    }

    const scene = this.scene;
    if (this.standaloneAtmosphere) {
      scene.clearColor = new Color4(0.55, 0.68, 0.76, 1);
      const sun = new DirectionalLight('pg-sun', new Vector3(-0.45, -1, -0.35), scene);
      sun.intensity = 2.4;
      const fill = new HemisphericLight('pg-fill', new Vector3(0, 1, 0), scene);
      fill.intensity = 0.5;
      this.lights.push(sun, fill);
    }

    this.buildMaterials();
    this.buildTrackSurface();
    this.buildRunoffAndPad();
    this.buildCheckpointVolumes();
    this.built = true;
    if (!this.silent) {
      console.log(
        `[proving-grounds] circuit ${this.totalLengthM.toFixed(1)} m, ` +
          `${this.meshes.length} meshes, ${this.waypoints.length} waypoints`,
      );
    }
    return this;
  }

  isBuilt(): boolean {
    return this.built && !this.disposed;
  }

  /** Idempotent teardown of everything this class created. Never throws. */
  dispose(): void {
    if (this.disposed) return;
    this.disposed = true;
    this.built = false;
    for (const mesh of this.meshes) ProvingGroundsScene.disposeQuietly(mesh);
    this.meshes = [];
    for (const mat of this.materials) ProvingGroundsScene.disposeQuietly(mat);
    this.materials = [];
    for (const light of this.lights) ProvingGroundsScene.disposeQuietly(light);
    this.lights = [];
    if (this.timer !== null) this.timer.dispose();
    this.timer = null;
    const scene = this.scene;
    this.scene = null;
    if (this.ownsScene && scene !== null) ProvingGroundsScene.disposeQuietly(scene);
    const engine = this.ownedEngine;
    this.ownedEngine = null;
    if (engine !== null) ProvingGroundsScene.disposeQuietly(engine);
  }

  // -- geometry queries ----------------------------------------------------------

  /** Closed-loop length in metres (≈ 1,200 m by construction). */
  get lengthM(): number {
    return this.totalLengthM;
  }

  /** Centreline waypoints at uniform ~0.5 m arc spacing (read-only). */
  getWaypoints(): readonly TrackWaypoint[] {
    return this.waypoints;
  }

  /** Metadata for the five circuit sections (Spec 17 §3.1). */
  getSections(): readonly CircuitSectionInfo[] {
    return this.sections;
  }

  /**
   * Track surface elevation at world (x, y), metres z-up: the centreline
   * elevation at the nearest arc position, tilted by the bank crossfall at
   * the query's signed lateral offset. Safe as the buggy's
   * `groundElevation` function while proving-grounds mode is active.
   */
  getTrackElevation(x: number, y: number): number {
    const near = this.locateOnTrack(x, y);
    const bank = bankAtS(near.s);
    // Crossfall is only meaningful across the half-width + curb; clamp so
    // far-off queries don't extrapolate the bank into the sky.
    return this.centreZ(near.s) + clamp(near.lateralM, -9, 9) * Math.tan(bank);
  }

  /** The centreline waypoint nearest to world (x, y). */
  getNearestWaypoint(x: number, y: number): TrackWaypoint {
    const near = this.locateOnTrack(x, y);
    return this.waypoints[this.sampleIndexAtS(near.s)];
  }

  /**
   * Where is (x, y) on the circuit: arc length s ∈ [0, L) and signed lateral
   * offset (metres; right of travel positive). Exact for any (x, y).
   */
  locateOnTrack(x: number, y: number): { s: number; lateralM: number } {
    const cx = Math.floor(x / this.gridCell);
    const cy = Math.floor(y / this.gridCell);
    let bestIdx = 0;
    let bestD = Number.POSITIVE_INFINITY;
    for (let ix = cx - 1; ix <= cx + 1; ix++) {
      for (let iy = cy - 1; iy <= cy + 1; iy++) {
        const bucket = this.grid.get(`${ix}|${iy}`);
        if (bucket === undefined) continue;
        for (const i of bucket) {
          const p = this.samples[i];
          const d = (p.x - x) * (p.x - x) + (p.y - y) * (p.y - y);
          if (d < bestD) {
            bestD = d;
            bestIdx = i;
          }
        }
      }
    }
    // No bucket hit (query far outside the hash): fall back to a coarse scan.
    if (!Number.isFinite(bestD)) {
      for (let i = 0; i < this.samples.length; i += 8) {
        const p = this.samples[i];
        const d = (p.x - x) * (p.x - x) + (p.y - y) * (p.y - y);
        if (d < bestD) {
          bestD = d;
          bestIdx = i;
        }
      }
    }
    // Refine: project onto the polyline segments around the winner.
    const L = this.totalLengthM;
    let bestS = this.samples[bestIdx].s;
    let bestDist = Math.sqrt(bestD);
    const lo = Math.max(0, bestIdx - 3);
    const hi = Math.min(this.samples.length - 2, bestIdx + 3);
    for (let i = lo; i <= hi; i++) {
      const a = this.samples[i];
      const b = this.samples[i + 1];
      const abx = b.x - a.x;
      const aby = b.y - a.y;
      const len2 = abx * abx + aby * aby;
      const t = len2 > 1e-12 ? clamp(((x - a.x) * abx + (y - a.y) * aby) / len2, 0, 1) : 0;
      const px = a.x + abx * t;
      const py = a.y + aby * t;
      const d = Math.hypot(x - px, y - py);
      if (d <= bestDist) {
        bestDist = d;
        bestS = a.s + (b.s - a.s) * t;
      }
    }
    // Signed lateral in the refined frame (right of travel positive).
    const ref = this.samples[this.sampleIndexAtS(bestS)];
    const lateral =
      (x - ref.x) * Math.sin(ref.heading) + (y - ref.y) * -Math.cos(ref.heading);
    return { s: wrapTrackS(bestS), lateralM: lateral };
  }

  /**
   * A physics-frame point at arc length s, lateral offset lRight (metres,
   * right of travel positive), riding the bank crossfall.
   */
  getPointAt(
    s: number,
    lateralM = 0,
  ): { x: number; y: number; z: number; headingRad: number } {
    const L = this.totalLengthM;
    const w = ((s % L) + L) % L;
    const f = w / this.sampleDs;
    const i = Math.min(this.samples.length - 2, Math.floor(f));
    const t = f - i;
    const a = this.samples[i];
    const b = this.samples[i + 1];
    const th = a.heading + (b.heading - a.heading) * t;
    const l = clamp(lateralM, -9, 9);
    return {
      x: a.x + (b.x - a.x) * t + Math.sin(th) * l,
      y: a.y + (b.y - a.y) * t - Math.cos(th) * l,
      z: this.centreZ(w) + l * Math.tan(bankAtS(w)),
      headingRad: th,
    };
  }

  /** Start/finish pose: on the line, facing forward along the straight. */
  getStartPose(): { x: number; y: number; z: number; headingRad: number } {
    return this.getPointAt(0);
  }

  // -- lap timing ------------------------------------------------------------------

  /** Build a fresh lap timer wired to this track's locator and gates. */
  createLapTimer(
    options: Omit<LapTimingOptions, 'trackLengthM' | 'gateS' | 'trapZone'> = {},
  ): LapTimingSystem {
    const timer = new LapTimingSystem({
      trackLengthM: this.totalLengthM,
      gateS: GATE_S,
      trapZone: SPEED_TRAP_ZONE,
      ...options,
    });
    timer.locate = (x: number, y: number) => this.locateOnTrack(x, y);
    return timer;
  }

  /** Step the scene's default lap timer (lazily created) one frame. */
  stepLapTiming(dt: number, x: number, y: number, speedMps: number): LapTelemetry {
    if (this.disposed) return this.timer?.getTelemetry() ?? nullTelemetry();
    if (this.timer === null) this.timer = this.createLapTimer();
    return this.timer.step(dt, x, y, speedMps);
  }

  /** Telemetry of the scene timer (null until one exists). */
  getLapTelemetry(): LapTelemetry | null {
    return this.timer?.getTelemetry() ?? null;
  }

  /** Reset the scene timer back to lap 1 (created if absent). */
  resetLapTiming(): void {
    if (this.disposed) return;
    if (this.timer === null) this.timer = this.createLapTimer();
    this.timer.reset();
  }

  /** Every Babylon mesh this scene created (asphalt, curbs, markings…). */
  getMeshes(): Mesh[] {
    return [...this.meshes];
  }

  // -- internals: geometry --------------------------------------------------------

  private centreZ(s: number): number {
    return elevationAtS(s);
  }

  private sampleIndexAtS(s: number): number {
    return clamp(Math.round(s / this.sampleDs), 0, this.samples.length - 1);
  }

  private buildWaypoints(): TrackWaypoint[] {
    const L = this.totalLengthM;
    const out: TrackWaypoint[] = [];
    for (const smp of this.samples) {
      let isCheckpoint = false;
      for (const g of GATE_S) {
        const d = Math.abs(smp.s - g);
        if (Math.min(d, L - d) <= this.sampleDs) {
          isCheckpoint = true;
          break;
        }
      }
      out.push({
        x: smp.x,
        y: smp.y,
        z: this.centreZ(smp.s),
        headingRad: smp.heading,
        bankAngleRad: bankAtS(smp.s),
        trackWidthM: TRACK_WIDTH_M,
        isCheckpoint,
        sectorIndex: sectorAtS(smp.s),
        sectionIndex: sectionAtS(smp.s),
        arcLengthM: smp.s,
      });
    }
    return out;
  }

  private buildSections(): CircuitSectionInfo[] {
    const bounds: Array<{
      index: 1 | 2 | 3 | 4 | 5;
      name: string;
      kind: CircuitSectionInfo['kind'];
      start: number;
      end: number;
    }> = [
      { index: 1, name: 'Straightaway Speed Trap', kind: 'straightaway', start: 0, end: S_S2 },
      { index: 2, name: 'Banked High-Speed Sweeper', kind: 'banked-sweeper', start: S_S2, end: S_S3 },
      { index: 3, name: 'Slalom S-Curves', kind: 'slalom', start: S_S3, end: S_S4 },
      { index: 4, name: 'Hairpin & Agility Zone', kind: 'hairpin', start: S_S4, end: S_S5 },
      { index: 5, name: 'Camber & Elevation Crest', kind: 'crest', start: S_S5, end: this.totalLengthM },
    ];
    return bounds.map((b) => {
      let peakBank = 0;
      let peakElev = 0;
      const n = Math.max(2, Math.round(b.end - b.start));
      for (let i = 0; i <= n; i++) {
        const s = b.start + ((b.end - b.start) * i) / n;
        peakBank = Math.max(peakBank, Math.abs(bankAtS(s)));
        peakElev = Math.max(peakElev, elevationAtS(s));
      }
      return {
        index: b.index,
        name: b.name,
        kind: b.kind,
        startS: b.start,
        endS: b.end,
        lengthM: b.end - b.start,
        peakBankRad: peakBank,
        peakElevationM: peakElev,
      };
    });
  }

  private buildGrid(): void {
    this.grid.clear();
    for (let i = 0; i < this.samples.length; i++) {
      const p = this.samples[i];
      const key = `${Math.floor(p.x / this.gridCell)}|${Math.floor(p.y / this.gridCell)}`;
      const bucket = this.grid.get(key);
      if (bucket !== undefined) bucket.push(i);
      else this.grid.set(key, [i]);
    }
  }

  /**
   * Surface point (physics frame) for (s, lateral) — centreline position +
   * right-hand offset + bank crossfall tilt.
   */
  private surfacePoint(s: number, l: number): { x: number; y: number; z: number } {
    const p = this.getPointAt(s, l);
    return p;
  }

  // -- internals: materials --------------------------------------------------------

  private buildMaterials(): void {
    const scene = this.scene as Scene;

    const asphalt = new PBRMaterial('pg-asphalt', scene);
    asphalt.albedoColor = new Color3(0.028, 0.029, 0.033);
    asphalt.metallic = 0.04;
    asphalt.roughness = 0.92;

    const white = new PBRMaterial('pg-paint-white', scene);
    white.albedoColor = new Color3(0.92, 0.92, 0.9);
    white.metallic = 0;
    white.roughness = 0.6;

    const red = new PBRMaterial('pg-paint-red', scene);
    red.albedoColor = new Color3(0.78, 0.05, 0.05);
    red.metallic = 0;
    red.roughness = 0.6;

    const yellow = new PBRMaterial('pg-paint-yellow', scene);
    yellow.albedoColor = new Color3(0.9, 0.78, 0.16);
    yellow.metallic = 0;
    yellow.roughness = 0.6;

    const gravel = new PBRMaterial('pg-gravel', scene);
    gravel.albedoColor = new Color3(0.16, 0.15, 0.14);
    gravel.metallic = 0;
    gravel.roughness = 1;

    const gate = new PBRMaterial('pg-gate', scene);
    gate.albedoColor = new Color3(1, 0.75, 0.1);
    gate.emissiveColor = new Color3(0.5, 0.36, 0.03);
    gate.metallic = 0.3;
    gate.roughness = 0.5;

    const gateFinish = new PBRMaterial('pg-gate-finish', scene);
    gateFinish.albedoColor = new Color3(0.2, 0.95, 0.45);
    gateFinish.emissiveColor = new Color3(0.06, 0.5, 0.2);
    gateFinish.metallic = 0.3;
    gateFinish.roughness = 0.5;

    this.asphaltMaterial = asphalt;
    this.paintWhiteMaterial = white;
    this.paintRedMaterial = red;
    this.paintYellowMaterial = yellow;
    this.gravelMaterial = gravel;
    this.gateMaterial = gate;
    this.gateFinishMaterial = gateFinish;
    this.materials.push(asphalt, white, red, yellow, gravel, gate, gateFinish);
  }

  // -- internals: mesh emission ------------------------------------------------------

  /**
   * Append one flat quad between arc bounds [s0, s1] and lateral offsets
   * [l0, l1] into the accumulator (emitted in Babylon's y-up frame).
   */
  private emitQuad(acc: QuadAccumulator, s0: number, s1: number, l0: number, l1: number): void {
    const p00 = this.surfacePoint(s0, l0);
    const p10 = this.surfacePoint(s1, l0);
    const p11 = this.surfacePoint(s1, l1);
    const p01 = this.surfacePoint(s0, l1);
    const ux = p10.x - p00.x;
    const uy = p10.y - p00.y;
    const uz = p10.z - p00.z;
    const vx = p01.x - p00.x;
    const vy = p01.y - p00.y;
    const vz = p01.z - p00.z;
    let nx = uy * vz - uz * vy;
    let ny = uz * vx - ux * vz;
    let nz = ux * vy - uy * vx;
    if (ny < 0) {
      nx = -nx;
      ny = -ny;
      nz = -nz;
    }
    const len = Math.hypot(nx, ny, nz) || 1;
    const base = acc.positions.length / 3;
    for (const p of [p00, p10, p11, p01]) {
      const b = worldToBabylon(p);
      acc.positions.push(b.x, b.y, b.z);
      // physics normal (nx, ny, nz↑) → babylon (nx, nz↑, −ny)
      acc.normals.push(nx / len, nz / len, -ny / len);
    }
    acc.uvs.push(s0 / 6, 0, s1 / 6, 0, s1 / 6, 1, s0 / 6, 1);
    acc.indices.push(base, base + 1, base + 2, base, base + 2, base + 3);
  }

  /** Finalise an accumulator as one Mesh (skips empty ones). */
  private finishMesh(name: string, acc: QuadAccumulator, material: PBRMaterial): Mesh | null {
    if (this.scene === null || acc.indices.length === 0) return null;
    const mesh = new Mesh(name, this.scene);
    const vd = new VertexData();
    vd.positions = acc.positions;
    vd.normals = acc.normals;
    vd.uvs = acc.uvs;
    vd.indices = acc.indices;
    vd.applyToMesh(mesh);
    mesh.material = material;
    this.meshes.push(mesh);
    return mesh;
  }

  private buildTrackSurface(): void {
    if (this.scene === null) return;
    const L = this.totalLengthM;
    const seg = 1; // 1 m quads along the ribbon
    const half = TRACK_WIDTH_M / 2;
    const curbOut = half + CURB_WIDTH_M;

    // Asphalt ribbon (one merged mesh).
    const asphalt = newAccumulator();
    for (let s = 0; s < L - 1e-6; s += seg) {
      this.emitQuad(asphalt, s, Math.min(s + seg, L), -half, half);
    }
    this.finishMesh('pg-asphalt', asphalt, this.asphaltMaterial as PBRMaterial);

    // Painted edge lines: 0.4 m bands just inside each asphalt edge.
    const edges = newAccumulator();
    for (let s = 0; s < L - 1e-6; s += seg) {
      const sEnd = Math.min(s + seg, L);
      this.emitQuad(edges, s, sEnd, half - 0.8, half - 0.4);
      this.emitQuad(edges, s, sEnd, -half + 0.4, -half + 0.8);
    }
    this.finishMesh('pg-edge-lines', edges, this.paintWhiteMaterial as PBRMaterial);

    // Dashed centreline: 3 m on / 3 m off, 0.15 m wide.
    const centre = newAccumulator();
    for (let s = 0; s < L - 1e-6; s += 6) {
      this.emitQuad(centre, s, Math.min(s + 3, L), -0.075, 0.075);
    }
    this.finishMesh('pg-centerline', centre, this.paintYellowMaterial as PBRMaterial);

    // Rumble strips: alternating red/white blocks outside both asphalt edges.
    const STRIPE = 1.2;
    const nStripes = Math.round(L / STRIPE);
    const redAcc = newAccumulator();
    const whiteAcc = newAccumulator();
    for (let i = 0; i < nStripes; i++) {
      const s = i * STRIPE;
      const sEnd = Math.min(s + STRIPE, L);
      const acc = i % 2 === 0 ? redAcc : whiteAcc;
      this.emitQuad(acc, s, sEnd, half, curbOut);
      this.emitQuad(acc, s, sEnd, -curbOut, -half);
    }
    this.finishMesh('pg-curb-red', redAcc, this.paintRedMaterial as PBRMaterial);
    this.finishMesh('pg-curb-white', whiteAcc, this.paintWhiteMaterial as PBRMaterial);
  }

  private buildRunoffAndPad(): void {
    const scene = this.scene as Scene;

    // Compacted-gravel pad under the whole circuit footprint.
    let minX = Infinity;
    let maxX = -Infinity;
    let minY = Infinity;
    let maxY = -Infinity;
    for (const p of this.samples) {
      if (p.x < minX) minX = p.x;
      if (p.x > maxX) maxX = p.x;
      if (p.y < minY) minY = p.y;
      if (p.y > maxY) maxY = p.y;
    }
    const pad = MeshBuilder.CreateGround(
      'pg-pad',
      { width: maxX - minX + 180, height: maxY - minY + 180, subdivisions: 1 },
      scene,
    );
    pad.position.copyFrom(
      worldToBabylon({ x: (minX + maxX) / 2, y: (minY + maxY) / 2, z: -0.08 }),
    );
    pad.material = this.gravelMaterial;
    this.meshes.push(pad);

    // Hairpin run-off: tarmac disc filling the inside of the Section 4 turn.
    const midS = (S_S4 + S_S5) / 2;
    const apex = this.getPointAt(midS, 0);
    const th = apex.headingRad;
    const runoff = MeshBuilder.CreateDisc(
      'pg-hairpin-runoff',
      { radius: HAIRPIN_RADIUS_M + 16, tessellation: 48 },
      scene,
    );
    runoff.rotation.x = Math.PI / 2; // disc faces up
    runoff.position.copyFrom(
      worldToBabylon({
        x: apex.x + Math.sin(th) * HAIRPIN_RADIUS_M,
        y: apex.y - Math.cos(th) * HAIRPIN_RADIUS_M,
        z: elevationAtS(midS) - 0.03,
      }),
    );
    runoff.material = this.gravelMaterial;
    this.meshes.push(runoff);
  }

  private buildCheckpointVolumes(): void {
    const scene = this.scene as Scene;
    const names = ['finish', 'sector-1', 'sector-2'];
    const half = TRACK_WIDTH_M / 2;

    for (let g = 0; g < GATE_S.length; g++) {
      const s = GATE_S[g];
      const mat = g === 0 ? (this.gateFinishMaterial as PBRMaterial) : (this.gateMaterial as PBRMaterial);
      const th = this.samples[this.sampleIndexAtS(s)].heading;
      // Yaw so the beam spans the lateral axis across the track.
      const yaw = Math.PI / 2 - th;

      for (const side of [-1, 1] as const) {
        const p = this.surfacePoint(s, side * (half + CURB_WIDTH_M + 0.6));
        const pillar = MeshBuilder.CreateBox(
          `pg-gate-${names[g]}-pillar-${side > 0 ? 'r' : 'l'}`,
          { width: 0.6, height: 5.2, depth: 0.6 },
          scene,
        );
        pillar.position.copyFrom(worldToBabylon({ x: p.x, y: p.y, z: p.z + 2.6 }));
        pillar.rotation.y = yaw;
        pillar.material = mat;
        this.meshes.push(pillar);
      }

      // Top beam across the track.
      const beamC = this.surfacePoint(s, 0);
      const beam = MeshBuilder.CreateBox(
        `pg-gate-${names[g]}-beam`,
        { width: TRACK_WIDTH_M + 2 * CURB_WIDTH_M + 1.8, height: 0.9, depth: 0.6 },
        scene,
      );
      beam.position.copyFrom(worldToBabylon({ x: beamC.x, y: beamC.y, z: beamC.z + 5.2 }));
      beam.rotation.y = yaw;
      beam.material = mat;
      this.meshes.push(beam);

      // Translucent trigger volume spanning the gate plane (timing aid).
      const vol = MeshBuilder.CreateBox(
        `pg-gate-${names[g]}-volume`,
        { width: TRACK_WIDTH_M, height: 4, depth: 0.35 },
        scene,
      );
      vol.position.copyFrom(worldToBabylon({ x: beamC.x, y: beamC.y, z: beamC.z + 2 }));
      vol.rotation.y = yaw;
      const volMat = mat.clone(`pg-gate-${names[g]}-vol`);
      volMat.alpha = 0.22;
      vol.material = volMat;
      vol.isPickable = false;
      this.materials.push(volMat);
      this.meshes.push(vol);
    }
  }

  private static disposeQuietly(thing: { dispose?: () => unknown } | null): void {
    try {
      thing?.dispose?.();
    } catch {
      /* already gone */
    }
  }
}

/** Zeroed telemetry snapshot (post-dispose safe value). */
function nullTelemetry(): LapTelemetry {
  return {
    currentLap: 0,
    currentLapTimeS: 0,
    bestLapTimeS: null,
    lastLapTimeS: null,
    sectorTimesS: [],
    currentSpeedKmh: 0,
    topSpeedKmh: 0,
    speedTrapKmh: null,
    sectorDeltaS: null,
  };
}

export default ProvingGroundsScene;
